version: "3"

services:
  fpm:
    build: # Info to build the Docker image
      context: . # Specify where the Dockerfile is located (e.g. in the root directory of the project)
      dockerfile: Dockerfile-php # Specify the name of the Dockerfile
    volumes:
     - ./webservice/:/var/www/promotions-assigment/ # Location of the project for php-fpm. Note this should be the same for NGINX.
     - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
     - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
     - symfony # Docker containers (services) that need to connect to each other should be on the same network.

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
     - ./webservice/:/var/www/promotions-assigment/
    ports:
     - 8001:80 # Ports that are exposed, you can connect to port 8001 to port 80 of the container.
    networks:
     - symfony

  db:
    image: mysql:5.6
    volumes:
    - dbservice:/var/lib/mysql:cached # Persist the database in a Docker volume.
    ports:
    - 3311:3306
    networks:
    - symfony

volumes:
  dbservice:

networks:
 symfony: